import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Montserrat } from 'next/font/google'
const montserrat=Montserrat({ weight:['300', '400', '700'],subsets:['latin'] })

export const metadata: Metadata = {
  title: "Gaming",
  description: "Generated by Walid Ashraf (Gaming Website)",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${montserrat.className} dark antialiased`}
      >
        {children}
        <p className="font-semibold">Gaming Website</p>
      </body>
    </html>
  );
}
